export interface WebTemplate {
  id: number;
  title: string;
  category: string;
  desc: string;
  status?: 'New' | 'Popular' | 'Coming Soon';
  imageColor: string;
  nodes: any; // Craft.js nodes structure
  features: string[];
}

export const WEB_TEMPLATES: Record<number, WebTemplate> = {
  1: {
    id: 1,
    title: 'Minimal Blog',
    category: 'Blog',
    desc: 'A clean, typography-focused blog template perfect for writers.',
    status: 'Popular',
    imageColor: 'from-pink-500 to-rose-500',
    features: ['Responsive Design', 'SEO Optimized', 'Dark Mode Support', 'Fast Loading'],
    nodes: {
      ROOT: {
        type: { resolvedName: 'Page' },
        isCanvas: true,
        props: {},
        displayName: 'Page',
        custom: {},
        hidden: false,
        nodes: ['minimalBlogContainer'],
        linkedNodes: {},
      },
      minimalBlogContainer: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: {},
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['blogHeader', 'blogHero', 'blogContent', 'blogFooter'],
        linkedNodes: {},
      },
      blogHeader: {
        type: { resolvedName: 'Section' },
        isCanvas: true,
        props: { background: '#ffffff', padding: 20 },
        displayName: 'Section',
        custom: {},
        hidden: false,
        nodes: ['headerContainer'],
        linkedNodes: {},
      },
      headerContainer: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: {},
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['headerRow'],
        linkedNodes: {},
      },
      headerRow: {
        type: { resolvedName: 'Row' },
        isCanvas: true,
        props: { alignItems: 'center', justifyContent: 'space-between' },
        displayName: 'Row',
        custom: {},
        hidden: false,
        nodes: ['logoColumn', 'navColumn'],
        linkedNodes: {},
      },
      logoColumn: {
        type: { resolvedName: 'Column' },
        isCanvas: true,
        props: {},
        displayName: 'Column',
        custom: {},
        hidden: false,
        nodes: ['blogLogo'],
        linkedNodes: {},
      },
      blogLogo: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'BlogSpace', fontSize: 24, fontWeight: 'bold', color: '#1e293b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      navColumn: {
        type: { resolvedName: 'Column' },
        isCanvas: true,
        props: {},
        displayName: 'Column',
        custom: {},
        hidden: false,
        nodes: ['navRow'],
        linkedNodes: {},
      },
      navRow: {
        type: { resolvedName: 'Row' },
        isCanvas: true,
        props: { gap: 24 },
        displayName: 'Row',
        custom: {},
        hidden: false,
        nodes: ['navHome', 'navArticles', 'navAbout', 'navContact'],
        linkedNodes: {},
      },
      navHome: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'Home', fontSize: 14, color: '#64748b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      navArticles: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'Articles', fontSize: 14, color: '#64748b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      navAbout: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'About', fontSize: 14, color: '#64748b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      navContact: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'Contact', fontSize: 14, color: '#64748b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      blogHero: {
        type: { resolvedName: 'Section' },
        isCanvas: true,
        props: { background: '#f8fafc', padding: 80 },
        displayName: 'Section',
        custom: {},
        hidden: false,
        nodes: ['heroContainer'],
        linkedNodes: {},
      },
      heroContainer: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { maxWidth: '800px' },
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['heroColumn'],
        linkedNodes: {},
      },
      heroColumn: {
        type: { resolvedName: 'Column' },
        isCanvas: true,
        props: { alignItems: 'center' },
        displayName: 'Column',
        custom: {},
        hidden: false,
        nodes: ['heroTitle', 'heroSubtitle', 'heroButton'],
        linkedNodes: {},
      },
      heroTitle: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { 
          text: 'Thoughtful Writing in a Noisy World', 
          fontSize: 48, 
          fontWeight: 'bold', 
          color: '#1e293b',
          textAlign: 'center'
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      heroSubtitle: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { 
          text: 'A minimalist blog template focused on content and readability. Perfect for writers who want to share their thoughts without distractions.', 
          fontSize: 18, 
          color: '#64748b',
          textAlign: 'center'
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      heroButton: {
        type: { resolvedName: 'Button' },
        isCanvas: false,
        props: { text: 'Start Reading', backgroundColor: '#3b82f6', color: '#ffffff', fontSize: 16 },
        displayName: 'Button',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      blogFooter: {
        type: { resolvedName: 'Section' },
        isCanvas: true,
        props: { background: '#1e293b', padding: 40 },
        displayName: 'Section',
        custom: {},
        hidden: false,
        nodes: ['footerContainer'],
        linkedNodes: {},
      },
      footerContainer: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: {},
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['footerContent', 'footerDivider', 'footerCopyright'],
        linkedNodes: {},
      },
      footerContent: {
        type: { resolvedName: 'Row' },
        isCanvas: true,
        props: { gap: 48, marginBottom: 32 },
        displayName: 'Row',
        custom: {},
        hidden: false,
        nodes: ['footerAbout', 'footerLinks', 'footerSocial'],
        linkedNodes: {},
      },
      footerAbout: {
        type: { resolvedName: 'Column' },
        isCanvas: true,
        props: {},
        displayName: 'Column',
        custom: {},
        hidden: false,
        nodes: ['footerLogo', 'footerDescription'],
        linkedNodes: {},
      },
      footerLogo: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'BlogSpace', fontSize: 20, fontWeight: 'bold', color: '#ffffff', marginBottom: 16 },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      footerDescription: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'A minimalist blog platform for thoughtful writers and readers.', fontSize: 14, color: '#cbd5e1' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      footerDivider: {
        type: { resolvedName: 'Divider' },
        isCanvas: false,
        props: { color: '#334155' },
        displayName: 'Divider',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      footerCopyright: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: '© 2024 BlogSpace. All rights reserved.', fontSize: 14, color: '#94a3b8', textAlign: 'center', marginTop: 24 },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
    },
  },
  2: {
    id: 2,
    title: 'SaaS Landing',
    category: 'Landing Page',
    desc: 'High-conversion landing page for modern software products.',
    status: 'New',
    imageColor: 'from-blue-500 to-cyan-500',
    features: ['High Conversion', 'Modern Design', 'Mobile Responsive', 'Performance Optimized'],
    nodes: {
      ROOT: {
        type: { resolvedName: 'Page' },
        isCanvas: true,
        props: {},
        displayName: 'Page',
        custom: {},
        hidden: false,
        nodes: ['saasContainer'],
        linkedNodes: {},
      },
      saasContainer: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: {},
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['saasHeader', 'saasHero'],
        linkedNodes: {},
      },
      saasHeader: {
        type: { resolvedName: 'Section' },
        isCanvas: true,
        props: { background: '#ffffff', padding: 20, shadow: 'sm' },
        displayName: 'Section',
        custom: {},
        hidden: false,
        nodes: ['headerContent'],
        linkedNodes: {},
      },
      headerContent: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: {},
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['headerRow'],
        linkedNodes: {},
      },
      headerRow: {
        type: { resolvedName: 'Row' },
        isCanvas: true,
        props: { alignItems: 'center', justifyContent: 'space-between' },
        displayName: 'Row',
        custom: {},
        hidden: false,
        nodes: ['saasLogo', 'headerNav', 'headerCta'],
        linkedNodes: {},
      },
      saasLogo: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'SaaSPro', fontSize: 24, fontWeight: 'bold', color: '#1e293b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      headerNav: {
        type: { resolvedName: 'Row' },
        isCanvas: true,
        props: { gap: 32 },
        displayName: 'Row',
        custom: {},
        hidden: false,
        nodes: ['navProduct', 'navSolutions', 'navPricing'],
        linkedNodes: {},
      },
      navProduct: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'Product', fontSize: 14, color: '#64748b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      navSolutions: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'Solutions', fontSize: 14, color: '#64748b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      navPricing: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'Pricing', fontSize: 14, color: '#64748b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      headerCta: {
        type: { resolvedName: 'Button' },
        isCanvas: false,
        props: { text: 'Get Started', backgroundColor: '#3b82f6', color: '#ffffff', fontSize: 14 },
        displayName: 'Button',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      saasHero: {
        type: { resolvedName: 'Section' },
        isCanvas: true,
        props: { background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', padding: 100 },
        displayName: 'Section',
        custom: {},
        hidden: false,
        nodes: ['heroContent'],
        linkedNodes: {},
      },
      heroContent: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { maxWidth: '800px' },
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['heroColumn'],
        linkedNodes: {},
      },
      heroColumn: {
        type: { resolvedName: 'Column' },
        isCanvas: true,
        props: { alignItems: 'center' },
        displayName: 'Column',
        custom: {},
        hidden: false,
        nodes: ['heroTitle', 'heroSubtitle', 'heroButtons'],
        linkedNodes: {},
      },
      heroTitle: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { 
          text: 'Transform Your Business with AI-Powered Solutions', 
          fontSize: 56, 
          fontWeight: 'bold', 
          color: '#ffffff',
          textAlign: 'center'
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      heroSubtitle: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { 
          text: 'The all-in-one platform that helps you automate workflows, analyze data, and grow your business 10x faster.', 
          fontSize: 20, 
          color: '#e2e8f0',
          textAlign: 'center'
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      heroButtons: {
        type: { resolvedName: 'Row' },
        isCanvas: true,
        props: { gap: 16, marginTop: 32 },
        displayName: 'Row',
        custom: {},
        hidden: false,
        nodes: ['heroCtaPrimary', 'heroCtaSecondary'],
        linkedNodes: {},
      },
      heroCtaPrimary: {
        type: { resolvedName: 'Button' },
        isCanvas: false,
        props: { text: 'Start Free Trial', backgroundColor: '#ffffff', color: '#667eea', fontSize: 16 },
        displayName: 'Button',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      heroCtaSecondary: {
        type: { resolvedName: 'Button' },
        isCanvas: false,
        props: { text: 'Schedule Demo', backgroundColor: 'transparent', color: '#ffffff', fontSize: 16, border: '2px solid #ffffff' },
        displayName: 'Button',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
    },
  },
  3: {
    id: 3,
    title: 'Portfolio V1',
    category: 'Portfolio',
    desc: 'Showcase your work with this elegant, grid-based portfolio.',
    status: undefined,
    imageColor: 'from-emerald-500 to-teal-500',
    features: ['Portfolio Grid', 'Project Showcase', 'Contact Form', 'Social Links'],
    nodes: {
      ROOT: {
        type: { resolvedName: 'Page' },
        isCanvas: true,
        props: {},
        displayName: 'Page',
        custom: {},
        hidden: false,
        nodes: ['portfolioContainer'],
        linkedNodes: {},
      },
      portfolioContainer: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: {},
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['portfolioHeader', 'portfolioHero'],
        linkedNodes: {},
      },
      portfolioHeader: {
        type: { resolvedName: 'Section' },
        isCanvas: true,
        props: { background: '#ffffff', padding: 20 },
        displayName: 'Section',
        custom: {},
        hidden: false,
        nodes: ['headerContainer'],
        linkedNodes: {},
      },
      headerContainer: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: {},
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['headerRow'],
        linkedNodes: {},
      },
      headerRow: {
        type: { resolvedName: 'Row' },
        isCanvas: true,
        props: { alignItems: 'center', justifyContent: 'space-between' },
        displayName: 'Row',
        custom: {},
        hidden: false,
        nodes: ['portfolioLogo', 'portfolioNav'],
        linkedNodes: {},
      },
      portfolioLogo: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'Portfolio', fontSize: 24, fontWeight: 'bold', color: '#1e293b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      portfolioNav: {
        type: { resolvedName: 'Row' },
        isCanvas: true,
        props: { gap: 24 },
        displayName: 'Row',
        custom: {},
        hidden: false,
        nodes: ['navWork', 'navAbout', 'navContact'],
        linkedNodes: {},
      },
      navWork: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'Work', fontSize: 14, color: '#64748b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      navAbout: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'About', fontSize: 14, color: '#64748b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      navContact: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { text: 'Contact', fontSize: 14, color: '#64748b' },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      portfolioHero: {
        type: { resolvedName: 'Section' },
        isCanvas: true,
        props: { background: '#f8fafc', padding: 80 },
        displayName: 'Section',
        custom: {},
        hidden: false,
        nodes: ['heroContainer'],
        linkedNodes: {},
      },
      heroContainer: {
        type: { resolvedName: 'Container' },
        isCanvas: true,
        props: { maxWidth: '800px' },
        displayName: 'Container',
        custom: {},
        hidden: false,
        nodes: ['heroColumn'],
        linkedNodes: {},
      },
      heroColumn: {
        type: { resolvedName: 'Column' },
        isCanvas: true,
        props: { alignItems: 'center' },
        displayName: 'Column',
        custom: {},
        hidden: false,
        nodes: ['heroTitle', 'heroSubtitle', 'heroButton'],
        linkedNodes: {},
      },
      heroTitle: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { 
          text: 'Creative Portfolio', 
          fontSize: 48, 
          fontWeight: 'bold', 
          color: '#1e293b',
          textAlign: 'center'
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      heroSubtitle: {
        type: { resolvedName: 'Text' },
        isCanvas: false,
        props: { 
          text: 'Showcase your best work with this elegant portfolio template. Perfect for designers, developers, and creatives.', 
          fontSize: 18, 
          color: '#64748b',
          textAlign: 'center'
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
      heroButton: {
        type: { resolvedName: 'Button' },
        isCanvas: false,
        props: { text: 'View Projects', backgroundColor: '#10b981', color: '#ffffff', fontSize: 16 },
        displayName: 'Button',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
      },
    },
  },
};

// Helper functions
export const getAllTemplates = (): WebTemplate[] => {
  return Object.values(WEB_TEMPLATES);
};

export const getTemplateById = (id: number): WebTemplate | undefined => {
  return WEB_TEMPLATES[id];
};

export const getTemplatesByCategory = (category: string): WebTemplate[] => {
  if (category === 'All') return getAllTemplates();
  return getAllTemplates().filter(template => template.category === category);
};