import type { CartLayoutProps, OrderTrackingLayoutProps, CheckoutFormProps, CategoryLayoutProps, ProductDetailsProps, ProductListingProps, ProductActionButton } from "./types";
import { defaultCartItems, defaultOrderTrackingItems, defaultTrackingSteps, defaultCategoryProducts, defaultSortOptions, defaultFilterGroups, defaultSubcategories, defaultListingProducts } from "./defaults";

// Settings are lazily referenced; callers must assign `.related.settings` themselves.

export const cartCraftProps: CartLayoutProps = {
  items: defaultCartItems,
  showOrderSummary: true,
  summaryPosition: "right",
  backgroundColor: "#f8fafc",
  cardBackgroundColor: "#ffffff",
  summaryBackgroundColor: "#ffffff",
  titleColor: "#0f172a",
  labelColor: "#334155",
  priceColor: "#475569",
  totalPriceColor: "#1e293b",
  borderColor: "#e2e8f0",
  buttonBackgroundColor: "#3b82f6",
  buttonTextColor: "#ffffff",
  secondaryButtonBackgroundColor: "transparent",
  secondaryButtonTextColor: "#3b82f6",
  removeButtonColor: "#ef4444",
  quantityButtonColor: "#f1f5f9",
  borderRadius: 12,
  buttonBorderRadius: 10,
  imageSize: 96,
  title: "Shopping Cart",
  subtotalLabel: "Subtotal",
  shippingLabel: "Shipping",
  discountLabel: "Discount",
  totalLabel: "Total",
  checkoutButtonText: "Proceed to Checkout",
  continueShoppingText: "← Continue Shopping",
  emptyCartText: "Your cart is empty",
  emptyCartSubtext: "Looks like you haven't added anything to your cart yet.",
  promoPlaceholder: "Enter promo code",
  showPromoCode: true,
  showShippingEstimate: true,
  showContinueShopping: true,
  showItemVariant: true,
  showItemImage: true,
  shippingCost: 9.99,
  discount: 0,
  taxRate: 0.08,
};

export const orderTrackingCraftProps: OrderTrackingLayoutProps = {
  orderNumber: "ORD-2026-00847",
  trackingNumber: "1Z999AA10123456784",
  currentStatus: "shipped",
  estimatedDelivery: "February 14, 2026",
  orderDate: "February 8, 2026",
  shippingName: "John Doe",
  shippingAddress: "123 Main Street, Apt 4B",
  shippingCity: "New York",
  shippingState: "NY",
  shippingZip: "10001",
  shippingCountry: "United States",
  carrierName: "UPS",
  carrierLogo: "",
  carrierTrackingUrl: "#",
  items: defaultOrderTrackingItems,
  steps: defaultTrackingSteps,
  showItemsSummary: true,
  showShippingAddress: true,
  showCarrierInfo: true,
  showContactSupport: true,
  showEstimatedDelivery: true,
  layoutMode: "vertical",
  backgroundColor: "#f8fafc",
  cardBackgroundColor: "#ffffff",
  titleColor: "#0f172a",
  labelColor: "#64748b",
  valueColor: "#1e293b",
  borderColor: "#e2e8f0",
  activeStepColor: "#3b82f6",
  completedStepColor: "#22c55e",
  pendingStepColor: "#cbd5e1",
  buttonBackgroundColor: "#3b82f6",
  buttonTextColor: "#ffffff",
  statusBadgeColor: "#dbeafe",
  statusBadgeTextColor: "#1d4ed8",
  borderRadius: 12,
  buttonBorderRadius: 10,
  title: "Order Tracking",
  contactButtonText: "Contact Support",
  itemsSummaryTitle: "Order Items",
  shippingTitle: "Shipping Address",
  carrierTitle: "Carrier Information",
};

export const checkoutCraftProps: CheckoutFormProps = {
  showOrderSummary: true,
  summaryPosition: "right",
  backgroundColor: "#f8fafc",
  formBackgroundColor: "#ffffff",
  summaryBackgroundColor: "#ffffff",
  labelColor: "#334155",
  inputBackgroundColor: "#f8fafc",
  inputTextColor: "#1e293b",
  inputBorderColor: "#e2e8f0",
  buttonBackgroundColor: "#3b82f6",
  buttonTextColor: "#ffffff",
  priceColor: "#475569",
  totalPriceColor: "#1e293b",
  borderRadius: 12,
  inputBorderRadius: 8,
  buttonBorderRadius: 10,
  title: "Checkout",
  titleColor: "#0f172a",
  subtotalLabel: "Subtotal",
  shippingLabel: "Shipping",
  taxLabel: "Tax",
  totalLabel: "Total",
  buttonText: "Place Order",
  subtotal: 279.98,
  shipping: 10.00,
  tax: 23.20,
};

export const categoryCraftProps: CategoryLayoutProps = {
  categoryName: "Electronics",
  categoryDescription: "Explore our latest tech products and gadgets",
  bannerImage: "",
  bannerHeight: 160,
  showCategoryHeader: true,
  showFilters: true,
  showSort: true,
  sortOptions: defaultSortOptions,
  filterGroups: defaultFilterGroups,
  showSidebar: false,
  subcategories: defaultSubcategories,
  columns: 4,
  gap: 20,
  backgroundColor: "#f8fafc",
  categoryNameColor: "#1e293b",
  categoryDescriptionColor: "#64748b",
  priceColor: "#3b82f6",
  originalPriceColor: "#9ca3af",
  discountBadgeColor: "#ef4444",
  productTitleColor: "#111827",
  cardBackgroundColor: "#ffffff",
  buttonColor: "#3b82f6",
  buttonTextColor: "#ffffff",
  ratingColor: "#facc15",
  cardBorderRadius: 12,
  cardShadow: true,
  imageHeight: 180,
  buttonVariant: "primary",
  buttonText: "Add to Cart",
  products: defaultCategoryProducts,
  productCount: 6,
  showDescription: false,
  showRating: true,
  showPagination: true,
  paginationStyle: "loadmore",
  productsPerPage: 8,
  emptyStateText: "No products found",
  showEmptyState: true,
};

export const productDetailsCraftProps: ProductDetailsProps = {
  productName: "Premium Wireless Headphones",
  productPrice: 199.99,
  discountPrice: 149.99,
  productImage: "https://placehold.co/500x500/3b82f6/ffffff?text=Product",
  galleryImages: [
    "https://placehold.co/500x500/3b82f6/ffffff?text=Image+1",
    "https://placehold.co/500x500/10b981/ffffff?text=Image+2",
    "https://placehold.co/500x500/f59e0b/ffffff?text=Image+3",
  ],
  productDescription: "High-quality audio experience with noise cancellation and 30-hour battery life.",
  fullDescription: "These premium wireless headphones deliver immersive sound, advanced ANC, and a comfortable fit for extended listening sessions.",
  specifications: "Driver: 40mm\nBluetooth: 5.3\nBattery: 30h\nCharge: USB-C\nWeight: 250g",
  reviewsEnabled: true,
  productRating: 4.5,
  productReviews: 128,
  inStock: true,
  stockCount: 25,
  backgroundColor: "#ffffff",
  titleColor: "#1e293b",
  priceColor: "#3b82f6",
  showRating: true,
  imageHeight: 400,
  layoutMode: "grid" as const,
  maxGalleryImages: 5,
  actionButtons: [
    { label: "Add to Cart", variant: "primary" },
    { label: "Buy Now", variant: "secondary" },
    { label: "\u2661 Wishlist", variant: "outline" },
  ] as ProductActionButton[],
};

export const productListingCraftProps: ProductListingProps = {
  title: "Our Products",
  subtitle: "Browse our collection of premium products",
  columns: 3,
  gap: 24,
  products: defaultListingProducts,
  backgroundColor: "#ffffff",
  titleColor: "#1e293b",
  priceColor: "#3b82f6",
  buttonVariant: "primary" as const,
  showDescription: true,
  cardBorderRadius: 12,
  cardShadow: true,
  cardHeight: "auto",
  imageHeight: 256,
};

/** Shared craft rules */
export const defaultCraftRules = {
  canMoveIn: () => false,
  canMoveOut: () => true,
  canDrag: () => true,
};

export const defaultCraftRulesWithDrop = {
  ...defaultCraftRules,
  canDrop: () => true,
  canDelete: () => true,
};
