"use client";

import React from "react";
import { Element } from "@craftjs/core";
import { Section } from "../../../design/_designComponents/Section/Section";
import { Container } from "../../../design/_designComponents/Container/Container";
import { Row } from "../../../design/_designComponents/Row/Row";
import { Column } from "../../../design/_designComponents/Column/Column";
import { Text } from "../../../design/_designComponents/Text/Text";
import { TemplateEntry } from "../../_types";
import { fonts } from "@/lib/theme";

export const NeoFooter: TemplateEntry = {
  label: "Neo Footer",
  description: "Neo branded footer block",
  preview: "Neo",
  category: "footer",
  element: React.createElement(
    Element as any,
    {
      is: Section as any,
      canvas: true,
      background: "#0d2c25",
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      backgroundVideo: "",
      strokePlacement: "mid",
      alignItems: "center",
      justifyContent: "center",
      isFreeform: false,
      position: "relative",
      zIndex: 0,
      top: "auto",
      right: "auto",
      bottom: "auto",
      left: "auto",
      overflow: "hidden",
      rotation: 0,
      flipHorizontal: false,
      flipVertical: false,
      height: "auto",
    },
      React.createElement(Element as any, {
        is: Container as any,
        canvas: true,
        background: "transparent",
        padding: 0,
        paddingTop: 0,
        paddingRight: 0,
        paddingBottom: 0,
        paddingLeft: 0,
        width: "1000px",
        height: "1000px",
        backgroundVideo: "",
        borderColor: "rgba(255,255,255,0.05)",
        borderWidth: 1,
        strokePlacement: "mid",
        position: "absolute",
        top: "-200px",
        right: "-200px",
        editorVisibility: "auto",
        rotation: 45,
      }),
      React.createElement(Element as any, {
        is: Container as any,
        canvas: true,
        background: "transparent",
        padding: 0,
        paddingTop: 0,
        paddingRight: 0,
        paddingBottom: 0,
        paddingLeft: 0,
        width: "800px",
        height: "800px",
        backgroundVideo: "",
        borderColor: "rgba(255,255,255,0.03)",
        borderWidth: 1,
        strokePlacement: "mid",
        position: "absolute",
        bottom: "-300px",
        left: "20%",
        editorVisibility: "auto",
        rotation: -45,
      }),
      React.createElement(
        Element as any,
        {
          is: Container as any,
          canvas: true,
          background: "transparent",
          padding: 0,
          paddingTop: 120,
          paddingRight: 80,
          paddingBottom: 80,
          paddingLeft: 80,
          width: "1920px",
          height: "542px",
          backgroundVideo: "",
          strokePlacement: "mid",
          alignItems: "stretch",
          position: "relative",
          zIndex: 10,
          editorVisibility: "auto",
          maxWidth: "1380px",
        },
        React.createElement(
          Element as any,
          {
            is: Row as any,
            canvas: true,
            strokePlacement: "mid",
            flexWrap: "nowrap",
            alignItems: "flex-start",
            justifyContent: "space-between",
            gap: 60,
            display: "flex",
          },
          React.createElement(
            Element as any,
            {
              is: Column as any,
              canvas: true,
              padding: 0,
              width: "50%",
              strokePlacement: "mid",
              gap: 0,
              display: "flex",
            },
            React.createElement(
              Element as any,
              {
                is: Row as any,
                canvas: true,
                marginBottom: 48,
                strokePlacement: "mid",
                flexWrap: "nowrap",
                alignItems: "center",
                display: "flex",
              },
              React.createElement(
                Element as any,
                {
                  is: Container as any,
                  canvas: true,
                  background: "transparent",
                  padding: 0,
                  paddingTop: 0,
                  paddingRight: 0,
                  paddingBottom: 0,
                  paddingLeft: 0,
                  width: "54px",
                  height: "54px",
                  backgroundVideo: "",
                  strokePlacement: "mid",
                  alignItems: "center",
                  justifyContent: "center",
                  position: "relative",
                  editorVisibility: "auto",
                },
                React.createElement(
                  Element as any,
                  {
                    is: Column as any,
                    canvas: true,
                    width: "18px",
                    height: "14px",
                    strokePlacement: "mid",
                    alignItems: "center",
                    justifyContent: "center",
                    gap: 3,
                    display: "flex",
                    position: "absolute",
                    bottom: "12px",
                  },
                  React.createElement(Element as any, {
                    is: Container as any,
                    canvas: true,
                    background: "#0d2c25",
                    padding: 0,
                    paddingTop: 0,
                    paddingRight: 0,
                    paddingBottom: 0,
                    paddingLeft: 0,
                    height: "2px",
                    backgroundVideo: "",
                    strokePlacement: "mid",
                    editorVisibility: "auto",
                  }),
                  React.createElement(Element as any, {
                    is: Container as any,
                    canvas: true,
                    background: "#0d2c25",
                    padding: 0,
                    paddingTop: 0,
                    paddingRight: 0,
                    paddingBottom: 0,
                    paddingLeft: 0,
                    height: "2px",
                    backgroundVideo: "",
                    strokePlacement: "mid",
                    editorVisibility: "auto",
                  }),
                  React.createElement(Element as any, {
                    is: Container as any,
                    canvas: true,
                    background: "#0d2c25",
                    padding: 0,
                    paddingTop: 0,
                    paddingRight: 0,
                    paddingBottom: 0,
                    paddingLeft: 0,
                    height: "2px",
                    backgroundVideo: "",
                    strokePlacement: "mid",
                    editorVisibility: "auto",
                  })
                )
              ),
              React.createElement(Text as any, {
                text: "FINDING NEO",
                fontSize: 32,
                fontFamily: fonts.uiRaw,
                fontWeight: "600",
                letterSpacing: "5px",
                color: "#ffffff",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "0px",
                right: "auto",
                bottom: "auto",
                left: "-47px",
                marginLeft: -18.374536871269317,
                textDecoration: "none",
              })
            ),
            React.createElement(Text as any, {
              text: "Empowering physicians with advanced multi-modal tools to improve treatment selection and patient outcomes.",
              fontSize: 22,
              fontFamily: fonts.uiRaw,
              lineHeight: 1.6,
              color: "#ffffff",
              position: "relative",
              display: "block",
              zIndex: 2,
              top: "auto",
              right: "auto",
              bottom: "auto",
              left: "auto",
              width: "90%",
              marginBottom: 64,
              textDecoration: "none",
            }),
            React.createElement(
              Element as any,
              {
                is: Row as any,
                canvas: true,
                marginBottom: 80,
                strokePlacement: "mid",
                flexWrap: "nowrap",
                alignItems: "center",
                gap: 0,
                display: "flex",
              },
              React.createElement(
                Element as any,
                {
                  is: Container as any,
                  canvas: true,
                  background: "transparent",
                  padding: 0,
                  paddingTop: 0,
                  paddingRight: 0,
                  paddingBottom: 0,
                  paddingLeft: 0,
                  marginRight: 24,
                  width: "48px",
                  height: "auto",
                  backgroundVideo: "",
                  strokePlacement: "mid",
                  alignItems: "center",
                  justifyContent: "center",
                  editorVisibility: "auto",
                },
                React.createElement(Text as any, {
                  text: "𝕏",
                  fontSize: 24,
                  fontFamily: fonts.uiRaw,
                  fontWeight: "500",
                  color: "#ffffff",
                  position: "relative",
                  display: "block",
                  zIndex: 2,
                  top: "auto",
                  right: "auto",
                  bottom: "auto",
                  left: "auto",
                  textDecoration: "none",
                })
              ),
              React.createElement(
                Element as any,
                {
                  is: Container as any,
                  canvas: true,
                  background: "transparent",
                  padding: 0,
                  paddingTop: 0,
                  paddingRight: 0,
                  paddingBottom: 0,
                  paddingLeft: 0,
                  marginRight: 24,
                  width: "48px",
                  height: "auto",
                  backgroundVideo: "",
                  strokePlacement: "mid",
                  alignItems: "center",
                  justifyContent: "center",
                  editorVisibility: "auto",
                },
                React.createElement(Text as any, {
                  text: "in",
                  fontSize: 24,
                  fontFamily: fonts.uiRaw,
                  fontWeight: "500",
                  color: "#ffffff",
                  position: "relative",
                  display: "block",
                  zIndex: 2,
                  top: "auto",
                  right: "auto",
                  bottom: "auto",
                  left: "auto",
                  textDecoration: "none",
                })
              ),
              React.createElement(
                Element as any,
                {
                  is: Container as any,
                  canvas: true,
                  background: "transparent",
                  padding: 0,
                  paddingTop: 0,
                  paddingRight: 0,
                  paddingBottom: 0,
                  paddingLeft: 0,
                  marginRight: 24,
                  width: "48px",
                  height: "auto",
                  backgroundVideo: "",
                  strokePlacement: "mid",
                  alignItems: "center",
                  justifyContent: "center",
                  editorVisibility: "auto",
                },
                React.createElement(Text as any, {
                  text: "📷",
                  fontSize: 24,
                  fontFamily: fonts.uiRaw,
                  fontWeight: "500",
                  color: "#ffffff",
                  position: "relative",
                  display: "block",
                  zIndex: 2,
                  top: "auto",
                  right: "auto",
                  bottom: "auto",
                  left: "auto",
                  textDecoration: "none",
                })
              ),
              React.createElement(
                Element as any,
                {
                  is: Container as any,
                  canvas: true,
                  background: "transparent",
                  padding: 0,
                  paddingTop: 0,
                  paddingRight: 0,
                  paddingBottom: 0,
                  paddingLeft: 0,
                  marginRight: 24,
                  width: "48px",
                  height: "auto",
                  backgroundVideo: "",
                  strokePlacement: "mid",
                  alignItems: "center",
                  justifyContent: "center",
                  editorVisibility: "auto",
                },
                React.createElement(Text as any, {
                  text: "fb",
                  fontSize: 24,
                  fontFamily: fonts.uiRaw,
                  fontWeight: "500",
                  color: "#ffffff",
                  position: "relative",
                  display: "block",
                  zIndex: 2,
                  top: "auto",
                  right: "auto",
                  bottom: "auto",
                  left: "auto",
                  textDecoration: "none",
                })
              )
            ),
            React.createElement(
              Element as any,
              {
                is: Container as any,
                canvas: true,
                background: "transparent",
                padding: 0,
                paddingTop: 18,
                paddingRight: 32,
                paddingBottom: 18,
                paddingLeft: 32,
                width: "184px",
                height: "68px",
                backgroundVideo: "",
                borderColor: "#ffffff",
                borderWidth: 1,
                strokePlacement: "mid",
                alignItems: "center",
                justifyContent: "center",
                editorVisibility: "auto",
                cursor: "pointer",
              },
              React.createElement(
                Element as any,
                {
                  is: Row as any,
                  canvas: true,
                  strokePlacement: "mid",
                  alignItems: "center",
                  justifyContent: "center",
                  gap: 12,
                  display: "flex",
                },
                React.createElement(Text as any, {
                  text: "︿",
                  fontSize: 20,
                  fontFamily: fonts.uiRaw,
                  fontWeight: "900",
                  color: "#ffffff",
                  position: "relative",
                  display: "block",
                  zIndex: 2,
                  top: "-4px",
                  right: "auto",
                  bottom: "auto",
                  left: "0px",
                  textDecoration: "none",
                }),
                React.createElement(Text as any, {
                  text: "BACK TO TOP",
                  fontSize: 14,
                  fontFamily: fonts.uiRaw,
                  fontWeight: "700",
                  letterSpacing: "3px",
                  color: "#ffffff",
                  position: "relative",
                  display: "block",
                  zIndex: 2,
                  top: "auto",
                  right: "auto",
                  bottom: "auto",
                  left: "auto",
                  textDecoration: "none",
                })
              )
            )
          ),
          React.createElement(
            Element as any,
            {
              is: Row as any,
              canvas: true,
              width: "45%",
              strokePlacement: "mid",
              alignItems: "flex-start",
              justifyContent: "flex-end",
              gap: 100,
              display: "flex",
            },
            React.createElement(
              Element as any,
              {
                is: Column as any,
                canvas: true,
                padding: 0,
                strokePlacement: "mid",
                gap: 0,
                display: "flex",
              },
              React.createElement(Text as any, {
                text: "Site Map",
                fontSize: 18,
                fontFamily: fonts.uiRaw,
                fontWeight: "700",
                letterSpacing: "1px",
                color: "#ffffff",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 40,
                textDecoration: "none",
              }),
              React.createElement(Text as any, {
                text: "Homepage",
                fontFamily: fonts.uiRaw,
                lineHeight: 1.4,
                color: "#cbd5e1",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 24,
                textDecoration: "underline",
              }),
              React.createElement(Text as any, {
                text: "Technology",
                fontFamily: fonts.uiRaw,
                lineHeight: 1.4,
                color: "#cbd5e1",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 24,
                textDecoration: "none",
              }),
              React.createElement(Text as any, {
                text: "Techneo",
                fontFamily: fonts.uiRaw,
                lineHeight: 1.4,
                color: "#cbd5e1",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 24,
                textDecoration: "none",
              }),
              React.createElement(Text as any, {
                text: "Resources & news",
                fontFamily: fonts.uiRaw,
                lineHeight: 1.4,
                color: "#cbd5e1",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 24,
                textDecoration: "none",
              }),
              React.createElement(Text as any, {
                text: "Careers",
                fontFamily: fonts.uiRaw,
                lineHeight: 1.4,
                color: "#cbd5e1",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 24,
                textDecoration: "none",
              }),
              React.createElement(Text as any, {
                text: "Contact Us",
                fontFamily: fonts.uiRaw,
                lineHeight: 1.4,
                color: "#cbd5e1",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 24,
                textDecoration: "none",
              }),
              React.createElement(Text as any, {
                text: "Portal",
                fontFamily: fonts.uiRaw,
                lineHeight: 1.4,
                color: "#cbd5e1",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 24,
                textDecoration: "none",
              })
            ),
            React.createElement(
              Element as any,
              {
                is: Column as any,
                canvas: true,
                padding: 0,
                strokePlacement: "mid",
                gap: 0,
                display: "flex",
              },
              React.createElement(Text as any, {
                text: "Legal",
                fontSize: 18,
                fontFamily: fonts.uiRaw,
                fontWeight: "700",
                letterSpacing: "1px",
                color: "#ffffff",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 40,
                textDecoration: "none",
              }),
              React.createElement(Text as any, {
                text: "Privacy Policy",
                fontFamily: fonts.uiRaw,
                lineHeight: 1.4,
                color: "#cbd5e1",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 24,
                textDecoration: "none",
              }),
              React.createElement(Text as any, {
                text: "Terms of Services",
                fontFamily: fonts.uiRaw,
                lineHeight: 1.4,
                color: "#cbd5e1",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 24,
                textDecoration: "none",
              }),
              React.createElement(Text as any, {
                text: "Lawyer's Corners",
                fontFamily: fonts.uiRaw,
                lineHeight: 1.4,
                color: "#cbd5e1",
                position: "relative",
                display: "block",
                zIndex: 2,
                top: "auto",
                right: "auto",
                bottom: "auto",
                left: "auto",
                marginBottom: 24,
                textDecoration: "none",
              })
            )
          )
        )
      ),
      React.createElement(
        Element as any,
        {
          is: Container as any,
          canvas: true,
          background: "#d2983b",
          padding: 0,
          paddingTop: 16,
          paddingRight: 0,
          paddingBottom: 16,
          paddingLeft: 0,
          height: "auto",
          backgroundVideo: "",
          strokePlacement: "mid",
          alignItems: "center",
          justifyContent: "center",
          zIndex: 20,
          editorVisibility: "auto",
        },
        React.createElement(Text as any, {
          text: "Copyright © 2026, Finding Neo, All Rights Reserved.",
          fontSize: 14,
          fontFamily: fonts.uiRaw,
          fontWeight: "500",
          position: "relative",
          display: "block",
          zIndex: 2,
          top: "auto",
          right: "auto",
          bottom: "auto",
          left: "auto",
          textDecoration: "none",
        })
      )
  ),
};
